### PR TITLE
ui: Change the document title dynamically

### PR DESCRIPTION
**Pull request by Etsija**
Screenshot from 2024-12-09 12-13-58

Screenshot from 2024-12-09 12-13-45

Screenshot from 2024-12-09 12-13-28

Please have a look at the commits for details.

### CODE REVIEW

**Comment by Etsija** [comment]
Wrong title (product name) is shown when returning from repository to organization level.

**Comment by Etsija** [comment]
Found a simple and (I think) elegant solution by using useMatch(). Ready for review.

**Comment by sschuberth** [comment]
@mmurto would you be able to help with this now that the local Docker compose setup again works with Keycloak?

**Comment by mmurto** [comment]
> @mmurto would you be able to help with this now that the local Docker compose setup again works with Keycloak?

I'll give this a go.

**Comment by Etsija** [comment]
This will be closed & replaced with a new PR that works better.

**Comment by sschuberth** [comment]
> This will be closed & replaced with a new PR that works better.

For reference: https://github.com/eclipse-apoapsis/ort-server/pull/1714

**Pull request closed without merging**
