### PR TITLE
ui: Delete ORT runs

### PR DESCRIPTION
**Pull request by Etsija**
Please see the commits for details.

Screenshot from 2024-11-30 11-57-46

Screenshot from 2024-11-30 11-58-08

### CODE REVIEW

**Comment by sschuberth** [comment]
Here's a semi-related thing I anyway wanted to bring up: When referring to runs, like in the delete confirmation dialog, I think we should have a general guideline whether to use local or global run IDs.

Here, a local run ID probably makes more sense, as that's what's visible in the row the user clicked on. But in any case I'd include the type of ID to all places in the UI that refer to IDs.

Also, for this case of the delete confirmation, I'd use a more "fluent" text without a colon saying

> Are you sure to delete the run with local ID 2?

Or actually, since this is a Yes / No question, but our choices are "Cancel" / "Delete", either rename the buttons or say

> Please confirm the deletion of the run with local ID 2.

and keep the buttons as they are. Opinions, @mmurto, @mnonnenmacher?

**Comment by Etsija** [comment]
> Here's a semi-related thing I anyway wanted to bring up: When referring to runs, like in the delete confirmation dialog, I think we should have a general guideline whether to use local or global run IDs.
> 
> Here, a local run ID probably makes more sense, as that's what's visible in the row the user clicked on. But in any case I'd include the type of ID to all places in the UI that refer to IDs.
> 
> Also, for this case of the delete confirmation, I'd use a more "fluent" text without a colon saying
> 
> > Are you sure to delete the run with local ID 2?
> 
> Or actually, since this is a Yes / No question, but our choices are "Cancel" / "Delete", either rename the buttons or say
> 
> > Please confirm the deletion of the run with local ID 2.
> 
> and keep the buttons as they are. Opinions, @mmurto, @mnonnenmacher?

It's a bit difficult to change that without losing the generality of the delete dialog, which basically composes the text to show in the dialog.

**Comment by mmurto** [comment]
> Here's a semi-related thing I anyway wanted to bring up: When referring to runs, like in the delete confirmation dialog, I think we should have a general guideline whether to use local or global run IDs.
> 
> Here, a local run ID probably makes more sense, as that's what's visible in the row the user clicked on. But in any case I'd include the type of ID to all places in the UI that refer to IDs.
> 
> Also, for this case of the delete confirmation, I'd use a more "fluent" text without a colon saying
> 
> > Are you sure to delete the run with local ID 2?
> 
> Or actually, since this is a Yes / No question, but our choices are "Cancel" / "Delete", either rename the buttons or say
> 
> > Please confirm the deletion of the run with local ID 2.
> 
> and keep the buttons as they are. Opinions, @mmurto, @mnonnenmacher?

IMO "local IDs" but using proper terminology for them, so "Run index". Could also mention the repository URL in the confirmation dialog to bring more context to it.

**Comment by mmurto** [comment]
> The confirmation text in the delete dialog component is defined as
> 
> ```
>           <AlertDialogDescription>
>             Are you sure you want to delete this {item.descriptor}:{' '}
>             <span className='font-bold'>{item.name}</span>?
>           </AlertDialogDescription>
> ```
> 
> We wanted to do this in this way, to avoid having to write a separate confirmation text to every single delete dialog in the whole UI, because that would be more error prone. Suggestions to improve this are welcome, but if we want a tailored confirmation message in each dialog, some of the generality will be lost - and I'd need to change every dialog. That is probably outside of the scope of this PR.

This is a little different than the other deletable items as it shouldn't be identifiable by single ID, but the combination of the repository and run index. I'd either make the generic dialog more generic or create a custom component for this.

**Comment by sschuberth** [comment]
> I'd either make the generic dialog more generic

I'd vote for that.

**Comment by Etsija** [comment]
@mmurto I rebased after your delete dialog simplifications (which were great!), see what you think of it now.

**Review by mmurto — APPROVED** [review]

**Pull request merged**
