### PR TITLE
docs: Convert README files from AsciiDoc to Markdown

### PR DESCRIPTION
**Pull request by mnonnenmacher**
Convert all readme files in the repository from AsciiDoc to Markdown to use the same lanugage for all of them. Markdown was chosen over AsciiDoc because it is the more commonly used format in open source projects and most developers are familiar with it.

While at it, format all of those files to use the one sentence per line approach to minimize the diffs when the files are edited.

The conversion was done by converting the files using asciidoctor and pandoc:

  asciidoctor -b docbook5 README.adoc
  pandoc -f docbook -t gfm README.xml -o README.md \
    --base-header-level=2 --wrap=preserve

Afterwards any problems were corrected manually.

Relates to #256.

### CODE REVIEW

**Comment by sschuberth** [comment]
> Relates to #256.

Why only "Relates" and not "Resolves"?

**Comment by mnonnenmacher** [comment]
> > Relates to #256.
> 
> Why only "Relates" and not "Resolves"?

The `docs` folder still contains adoc files. Those files I do not want to just convert but largely rewrite as they are pretty outdated.

**Review by bs-ondem — APPROVED** [review]

**Comment by mmurto** [comment]
> While at it, format all of those files to use the one sentence per line approach to minimize the diffs when the files are edited.

One option (that I personally prefer, but opinions of course vary :)) would be to use Prettier for markdown files with a set line width like 80 or 100. That would make all Markdown files consistent, althogh the diffs may not be that good, even though IMO readable enough. It could also be nice to enable [Markdownlint](https://github.com/DavidAnson/markdownlint).

**Comment by oheger-bosch** [comment]
Since I have contributed a significant part of the documentation, I would have been nice if I had been asked for my opinion as well.

**Comment by mnonnenmacher** [comment]
> Since I have contributed a significant part of the documentation, it would have been nice if I had been asked for my opinion as well.

@oheger-bosch Sorry if that was against your preference, please add your perspective to #256, I have just added a comment explaining why I prefer Markdown.

**Pull request merged**
